#!/bin/bash

NEEDED_COMMANDS="pandoc xelatex"

for cmd in ${NEEDED_COMMANDS} ; do
    if ! which ${cmd} >/dev/null; then
        echo Please install ${cmd}!
        exit -1
    fi
done

echo "You're good!"
